//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PitchPitch.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PitchPitch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   録音 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceTypeName_Capture {
            get {
                return ResourceManager.GetString("DeviceTypeName_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceTypeName_Render {
            get {
                return ResourceManager.GetString("DeviceTypeName_Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PitchPitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dirname_Config {
            get {
                return ResourceManager.GetString("Dirname_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dirname_Font {
            get {
                return ResourceManager.GetString("Dirname_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dirname_Map {
            get {
                return ResourceManager.GetString("Dirname_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returnを押したまま発声して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Explanation_Calibration {
            get {
                return ResourceManager.GetString("Explanation_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑↓←→で選択，Returnで決定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Explanation_MapSelect {
            get {
                return ResourceManager.GetString("Explanation_MapSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注意: このゲームでは酸欠・喉の痛み・頭痛が発生することがあります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Explanation_TitleAlert {
            get {
                return ResourceManager.GetString("Explanation_TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mplus-2c-black.ttf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_DefaultP {
            get {
                return ResourceManager.GetString("Font_DefaultP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mplus-2m-bold.ttf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Font_DefaultTT {
            get {
                return ResourceManager.GetString("Font_DefaultTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTitle_AudioDevices {
            get {
                return ResourceManager.GetString("HeaderTitle_AudioDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音域設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTitle_Calibration {
            get {
                return ResourceManager.GetString("HeaderTitle_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLEAR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTitle_Clear {
            get {
                return ResourceManager.GetString("HeaderTitle_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GAME OVER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTitle_GameOver {
            get {
                return ResourceManager.GetString("HeaderTitle_GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAP SELECT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTitle_MapSelect {
            get {
                return ResourceManager.GetString("HeaderTitle_MapSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OPTION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTitle_Option {
            get {
                return ResourceManager.GetString("HeaderTitle_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PAUSE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeaderTitle_Pause {
            get {
                return ResourceManager.GetString("HeaderTitle_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_EndlessMap {
            get {
                return ResourceManager.GetString("MenuItem_EndlessMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_MapSelect {
            get {
                return ResourceManager.GetString("MenuItem_MapSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_Option {
            get {
                return ResourceManager.GetString("MenuItem_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   練習用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_PracticeMap {
            get {
                return ResourceManager.GetString("MenuItem_PracticeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_Quit {
            get {
                return ResourceManager.GetString("MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランダム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_RandomMap {
            get {
                return ResourceManager.GetString("MenuItem_RandomMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ再読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_ReloadMap {
            get {
                return ResourceManager.GetString("MenuItem_ReloadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_ResumeGame {
            get {
                return ResourceManager.GetString("MenuItem_ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_RetryStage {
            get {
                return ResourceManager.GetString("MenuItem_RetryStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_ReturnTitle {
            get {
                return ResourceManager.GetString("MenuItem_ReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItem_StartGame {
            get {
                return ResourceManager.GetString("MenuItem_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計測中… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_Calibrating {
            get {
                return ResourceManager.GetString("Str_Calibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高音 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_MaxPitch {
            get {
                return ResourceManager.GetString("Str_MaxPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低音 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Str_MinPitch {
            get {
                return ResourceManager.GetString("Str_MinPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pitch Pitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
